name: Default parser tests

on: 
  push:
    paths:
      - 'parser-default/**'
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Navigate to parser
        run: cd parser-default

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test
