name: Default parser tests

on: 
  push:
    paths:
      - parser-default/**
      - .github/workflows/tests-parser-default.yml
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and Run tests
        run: |
          cd parser-default
          npm install
          npm run test
